### ISSUE TITLE
Datos persistentes para pedir token y landing

### ISSUE THREAD

**Issue by Leticia-23** [UNIZAR-30226-2021-07/app#62]
Tanto el inicio de sesión, como el conseguir distintos datos de la api una vez que sales de la app, dejan de existir y se inicializa todo. Hay que guardar datos de forma persistente para si sales de la app y luego vuelvas no se pierdan. 
Guardar user (nombre y correo), el token (este habrá que actualizarlo cada vez que se vuelva a pedir, y demás datos que se vean necesarios cargar solo la primera vez que se inicia sesión para tenerlos hasta que se cierre, y  durante las partidas algunos habrá que actualizarlos.

**Comment by Tomenos18** [comment]
Considero necesarios sólo correo y contraseña, ya que a partir de estos 2, con peticiones http al servidor se puede conseguir el resto de datos relevantes.
